import Head from 'next/head'
import { useRouter } from 'next/router'
import React, { useEffect, useState } from 'react'
import { useSelector } from 'react-redux'
import CheckoutProduct from '../components/CheckoutProduct'
import Header from '../components/Header'
import Button from '../components/Helper/Button'
import { selectBasket } from '../redux/slices/basketSlice'

function Checkout() {
  const items = useSelector(selectBasket)
  const router = useRouter()

  const [groupedItemsBasket, setGroupedItemsBasket] = useState({} as {[key: string]: Product[]})

  useEffect(() => {
    const groupItems = items.reduce((result, item) => {
        (result[item._id] = result[item._id] || []).push(item)

        return result
    }, {} as {[key: string]: Product[]})

    setGroupedItemsBasket(groupItems)
  }, [items])

  return (
    <>
      <Head>
        <title>Bag - Apple</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className="mx-auto mt-6 max-w-5xl space-y-4 pb-24">
        <h1 className="text-3xl font-semibold lg:text-4xl">
          {items.length > 0 ? 'Review your bag.' : 'Your bag is empty.'}
        </h1>
        <p className="text-lg font-thin italic">Free delivery and free returns.</p>
        {items.length === 0 && (
          <Button title="Continue shopping" onClick={() => router.push('/')} />
        )}

        {items.length > 0 && (
            <div>
                {Object.entries(groupedItemsBasket).map(([key, items]) => (
                    <CheckoutProduct key={key} id={key} items={items} />
                ))}
            </div>
        )}
      </main>
    </>
  )
}

export default Checkout
