import axios from 'axios'
import type { GetServerSideProps } from 'next'
import Head from 'next/head'
import Banner from '../components/Banner'
import Header from '../components/Header'
import Promotions from '../components/Promotions'

interface Props {
  categories: Category[]
  products: Product[]
}

const Home = ({ categories, products }: Props) => {
  return (
    <>
      <Head>
        <title>Apple Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className="relative h-[200vh] bg-[#e7ecee]">
        <Banner />
      </main>

      <Promotions categories={categories} products={products} />
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async () => {
  const { data: categories } = await axios.get(`${process.env.NEXT_PUBLIC_BASE_URL}/api/categories`)
  const { data: products } = await axios.get(`${process.env.NEXT_PUBLIC_BASE_URL}/api/products`)

  return {
    props: {
      categories,
      products,
    },
  }
}

export default Home
