import axios from 'axios'
import type { GetServerSideProps } from 'next'
import Head from 'next/head'
import Banner from '../components/Banner'
import Basket from '../components/Basket'
import Header from '../components/Header'
import Promotions from '../components/Promotions'

import { getSession } from 'next-auth/react'
import type { Session } from 'next-auth'
import Adverisement from '../components/Adverisement'

interface Props {
  categories: Category[]
  products: Product[]
  session: Session
}

const Home = ({ categories, products, session }: Props) => {
  return (
    <>
      <Head>
        <title>Apple Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className="relative h-[200vh] bg-[#e7ecee]">
        <Banner />
      </main>

      <Promotions categories={categories} products={products} />
      <Adverisement />
      <Basket />
    </>
  )
}

// Make sure the avatar is loaded in serverside rendering
export const getServerSideProps: GetServerSideProps = async (context) => {
  const { data: categories } = await axios.get(`${process.env.NEXT_PUBLIC_BASE_URL}/api/categories`)
  const { data: products } = await axios.get(`${process.env.NEXT_PUBLIC_BASE_URL}/api/products`)
  const session = await getSession(context)

  return {
    props: {
      categories,
      products,
      session,
    },
  }
}

export default Home
